# Parameter file for benchmarking
dataset_path: "/home/cesar/Documents/phd/datasets/EUROC/MH_01_easy/mav0/cam0"

# choose execution mode
debug: False
enable_tracker: True
enable_matcher: False
nimages: 100
threshold_tracks: 400

# Parameters of the keypoint detector
nrows: 1
ncols: 1

detector: "orb"
threshold_fast: 30

npoints: 1000
scale_factor: 1.2
nlevels_pyramids: 8

# Parameters feature tracker

tracker_width: 21
tracker_height: 21
klt_max_err: 0.2
nlevels_pyramids_klt: 3

# Parameters feature matcher

matcher_width: 21
matcher_height: 21
threshold_matching: 64


