# Parameter file for benchmarking
# dataset_path: "/home/cesar/Documents/phd/datasets/EUROC/MH_01_easy/mav0/cam0"
dataset_path: "/home/mfourmy/Documents/Phd_LAAS/data/Euroc/MH_01_easy/mav0/cam0"

# print stuff, show images (buggy right now)
debug: False

# choose execution mode (either tracking or matching)
enable_tracker: True
enable_matcher: False

# number of images to take a look at
max_nb_frames: 100

# main_sequence: when the number of tracks drop below this level, detect new features (only implemented for KLT tracking)
threshold_tracks: 400


# Parameters of the keypoint detector
nrows: 1
ncols: 1

# 2 detectors possible: "orb" and "fast"
# - orb works both for tracking and matching
# - fast works for tracking and but matching will throw an error since cv::detectAndCompute is not implemented
detector: "fast"
threshold_fast: 30

# ORB params
nb_orb_detected: 1000
scale_factor: 1.2
nlevels_pyramids: 8

# Lucas Kanade tracker params
klt_patch_size: 15
klt_max_err: 0.2
nlevels_pyramids_klt: 3
precompute_pyramids: False
pyr_with_derivatives: False
klt_use_backward: False

# Feature matching params
matcher_width: 21
matcher_height: 21
threshold_matching: 64


